config/routes.rb
Rails.application.routes.draw do
  get 'control/game'

  get 'control/score'

   get 'game', to: 'control#game'
   get '/', to: 'control#game'
   get 'score', to: 'control#score'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/control_controller.rb
class ControlController < ApplicationController
  def game
    @grid = generate_grid(8)
  end

  def score
    if session[:nb_of_games]
     session[:nb_of_games] += 1
    else
     session[:nb_of_games]=1
    end

    if session[:scores]
      session[:average_score] += session[:average_score]
    else

    end





    @start_time = Time.parse(params[:start_time])
    @attempt = params[:query]
    @grid = params[:grid].split("")
    @end_time = Time.now
    @result = run_game(@attempt, @grid, @start_time, @end_time)
  end

  require 'open-uri'
  require 'json'

  def generate_grid(grid_size)
    Array.new(grid_size) { ('A'..'Z').to_a[rand(26)] }
  end


  def included?(guess, grid)
    guess.split("").all? { |letter| guess.count(letter) <= grid.count(letter) }
  end

  def compute_score(attempt, time_taken)
    (time_taken > 60.0) ? 0 : attempt.size * (1.0 - time_taken / 60.0)
  end

  def run_game(attempt, grid, start_time, end_time)
    result = { time: (end_time - start_time).round(2) }
    result[:translation] = get_translation(attempt)
    result[:score], result[:message] = score_and_message(attempt, result[:translation], grid, result[:time])

    result
  end

  def score_and_message(attempt, translation, grid, time)
    if included?(attempt.upcase, grid)
      if translation
        score = compute_score(attempt, time)
        [score, "well done"]
      else
        [0, "not an english word"]
      end
    else
      [0, "not in the grid"]
    end
  end

  def get_translation(word)
    api_key = "cb7f3261-f193-44af-9ac8-b6ee79a53125"
    begin
      response = open("https://api-platform.systran.net/translation/text/translate?source=en&target=fr&key=#{api_key}&input=#{word}")
      json = JSON.parse(response.read.to_s)
      raise
      if json['outputs'] && json['outputs'][0] && json['outputs'][0]['output'] && json['outputs'][0]['output'] != word
        return json['outputs'][0]['output']
      end
    rescue
      if File.read('/usr/share/dict/words').upcase.split("\n").include? word.upcase
        return word
      else
        return nil
      end
    end
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/control_helper.rb
module ControlHelper
end

app/views/control/game.html.erb
<img src="https://media.giphy.com/media/l0IycI0rreFNQwmSQ/giphy.gif" alt="..." class="img-rounded">
<h1>Control#game</h1>
<p>Find me in app/views/control/game.html.erb</p>

<form action="/score" class="form-inline" style="padding: 20px;">
  <label for="question">Generating grid</label>
  <p> <%= @grid %> </p>
  <input type="hidden" name="grid" value='<%= @grid.join %>' >

  <input type="hidden" name="start_time" value='<%= Time.now %>' >


  <input type="text" id="question" name="query" placeholder="Your best word ?">
  <input class="btn btn-primary btn-lg" type="submit" value="Go on!">
  <%= link_to "Regenerate ?", game_path, class:"btn btn-danger btn-lg" %>
</form>

app/views/control/score.html.erb
<h1>Control#score</h1>
<p>Find me in app/views/control/score.html.erb</p>

<p>Start time : <%= @start_time%></p>
<p>End time : <%= @end_time%></p>

<p>Résultat <%= @result %></p>

<p>Vous avez marqué <%= @result[:score] %>points</p>

<p>Trouvé en <%= @result[:time]%> secondes</p>

<p>Cela signifie <%= @result[:translation]%></p>
<%= link_to "New game ?", game_path, class:"btn btn-primary" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsLongestWordGame</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>